export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALURE = "LOGIN_FALURE";
export const LOGOUT = "LOGOUT";
export const FALHA = "FALHA";
export const PERSIST_TOKEN = "PERSIST_TOKEN";

export const FUNCIONARIO_REQUEST = "FUNCIONARIO_REQUEST";
export const FUNCIONARIO_SUCCESS = "FUNCIONARIO_SUCCESS";
export const FUNCIONARIO_FALURE = "FUNCIONARIO_FALURE";

export const FUNCIONARIO_EDITAR_REQUEST = "FUNCIONARIO_EDITAR_REQUEST";
export const FUNCIONARIO_EDITAR_SUCCESS = "FUNCIONARIO_EDITAR_SUCCESS";
export const FUNCIONARIO_EDITAR_FALURE = "FUNCIONARIO_EDITAR_FALURE";

export const FUNCIONARIO_BUSCAR_REQUEST = "FUNCIONARIO_BUSCAR_REQUEST";
export const FUNCIONARIO_BUSCAR_SUCCESS = "FUNCIONARIO_BUSCAR_SUCCESS";
export const FUNCIONARIO_BUSCAR_FALURE = "FUNCIONARIO_BUSCAR_FALURE";

export const FUNCIONARIO_CRIAR_COM_FOTO = "FUNCIONARIO_CRIAR_COM_FOTO";
export const FUNCIONARIO_EDITAR_COM_FOTO = "FUNCIONARIO_EDITAR_COM_FOTO";

// -------------------------------------------------------------------

export const CHAMADO_REQUEST = "CHAMADO_REQUEST";
export const CHAMADO_SUCCESS = "CHAMADO_SUCCESS";
export const CHAMADO_FALURE = "CHAMADO_FALURE";

export const CHAMADOS_REQUEST = "CHAMADOS_REQUEST";
export const CHAMADOS_SUCCESS = "CHAMADOS_SUCCESS";
export const CHAMADOS_FALURE = "CHAMADOS_FALURE";

export const EDITAR_CHAMADO_REQUEST = "EDITAR_CHAMADO_REQUEST";
export const EDITAR_CHAMADO_SUCCESS = "EDITAR_CHAMADO_SUCCESS";
export const EDITAR_CHAMADO_FALURE = "EDITAR_CHAMADO_FALURE";

export const DELETAR_CHAMADO_REQUEST = 'DELETAR_CHAMADO_REQUEST';
export const DELETAR_CHAMADO_SUCCESS = 'DELETAR_CHAMADO_SUCCESS';
export const DELETAR_CHAMADO_FALURE = 'DELETAR_CHAMADO_FALURE';

// ----------------------------------------------------------------

export const EMPRESA_REQUEST = 'EMPRESA_REQUEST';
export const EMPRESA_SUCCESS = 'EMPRESA_SUCCESS';
export const EMPRESA_FALURE = 'EMPRESA_FALURE';

// -----------------------------------------------------------------

export const STATUS_REQUEST = "STATUS_REQUEST";
export const STATUS_FALURE = "STATUS_FALURE";
export const STAUTS_SUCCESS = "STAUTS_SUCCESS";

export const EDITAR_STATUS_REQUEST =  "EDITAR_STATUS_REQUEST";
export const EDITAR_STATUS_FALURE = "ESDITAR_TATUS_FALURE";
export const EDITAR_STAUTS_SUCCESS =  "EDITAR_STAUTS_SUCCESS";

export const CRIAR_STATUS_REQUEST = "CRIAR_STATUS_REQUEST";
export const CRIAR_STATUS_FALURE = "CRIAR_STATUS_FALURE";
export const CRIAR_STAUTS_SUCCESS = "CRIAR_STAUTS_SUCCESS";

export const DELETAR_STATUS_REQUEST = "DELETAR_STATUS_REQUEST";
export const DELETAR_STATUS_FALURE = "DELETAR_STATUS_FALURE";
export const DELETAR_STAUTS_SUCCESS = "DELETAR_STAUTS_SUCCESS";


export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_FALURE = "GET_STATUS_FALURE";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";

export const EXEC_PROCEDURE_REQUEST = 'EXEC_PROCEDURE_REQUEST';
export const EXEC_PROCEDURE_FALURE = 'EXEC_PROCEDURE_FALURE';
export const EXEC_PROCEDURE_SUCCESS = 'EXEC_PROCEDURE_SUCCESS';

export const ISLOADING = "ISLOADING";

export const SETORES_REQUEST = 'SETORES_REQUEST';
export const SETORES_SUCCESS = 'SETORES_SUCCESS';
export const SETORES_FALURE = 'SETORES_FALURE';

export const CRIAR_SETORES_REQUEST = 'CRIAR_SETORES_REQUEST';
export const CRIAR_SETORES_SUCCESS = 'CRIAR_SETORES_SUCCESS';
export const CRIAR_SETORES_FALURE = 'CRIAR_SETORES_FALURE';

export const EDITAR_SETORES_REQUEST = 'EDITAR_SETORES_REQUEST';
export const EDITAR_SETORES_SUCCESS = 'EDITAR_SETORES_SUCCESS';
export const EDITAR_SETORES_FALURE = 'EDITAR_SETORES_FALURE';

export const DELETAR_SETORES_REQUEST = 'DELETAR_SETORES_REQUEST';
export const DELETAR_SETORES_SUCCESS = 'DELETAR_SETORES_SUCCESS';
export const DELETAR_SETORES_FALURE = 'DELETAR_SETORES_FALURE';

export const GET_CHAT = 'GET_CHAT'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FALURE = 'GET_CHAT_FALURE'

export const ADD_MESSAGE_CHAT_REQUEST = 'ADD_MESSAGE_CHAT_REQUEST'
export const ADD_MESSAGE_CHAT_SUCCESS = 'ADD_MESSAGE_CHAT_SUCCESS'
export const ADD_MESSAGE_CHAT_FALURE = 'ADD_MESSAGE_CHAT_FALURE'

export const UPDATE_MESSAGE_CHAT_REQUEST = 'UPDATE_MESSAGE_CHAT_REQUEST'
export const UPDATE_MESSAGE_CHAT_SUCCESS = 'UPDATE_MESSAGE_CHAT_SUCCESS'
export const UPDATE_MESSAGE_CHAT_FALURE = 'UPDATE_MESSAGE_CHAT_FALURE'

export const DELETE_MESSAGE_CHAT_REQUEST = 'DELETE_MESSAGE_CHAT_REQUEST'
export const DELETE_MESSAGE_CHAT_SUCCESS = 'DELETE_MESSAGE_CHAT_SUCCESS'
export const DELETE_MESSAGE_CHAT_FALURE = 'DELETE_MESSAGE_CHAT_FALURE'

export const RESET_CHAT = 'RESET_CHAT' 

export const COMENTARIO_CRIAR_REQUEST = "COMENTARIO_CRIAR_REQUEST";
export const COMENTARIO_CRIAR_SUCCESS = "COMENTARIO_CRIAR_SUCCESS";
export const COMENTARIO_CRIAR_FALURE = "COMENTARIO_CRIAR_FALURE";

export const COMENTARIO_EDITAR_REQUEST = "COMENTARIO_EDITAR_REQUEST";
export const COMENTARIO_EDITAR_SUCCESS = "COMENTARIO_EDITAR_SUCCESS";
export const COMENTARIO_EDITAR_FALURE = "COMENTARIO_EDITAR_FALURE";

export const COMENTARIO_BUSCAR_REQUEST = "COMENTARIO_BUSCAR_REQUEST";
export const COMENTARIO_BUSCAR_SUCCESS = "COMENTARIO_BUSCAR_SUCCESS";
export const COMENTARIO_BUSCAR_FALURE = "COMENTARIO_BUSCAR_FALURE";

export const COMENTARIO_DOWNLOAD_REQUEST = "COMENTARIO_DOWNLOAD_REQUEST";
export const COMENTARIO_DOWNLOAD_SUCCESS = "COMENTARIO_DOWNLOAD_SUCCESS";
export const COMENTARIO_DOWNLOAD_FALURE = "COMENTARIO_DOWNLOAD_FALURE";

export const COMENTARIO_DELETAR_REQUEST = "COMENTARIO_DELETAR_REQUEST";
export const COMENTARIO_DELETAR_SUCCESS = "COMENTARIO_DELETAR_SUCCESS";
export const COMENTARIO_DELETAR_FALURE = "COMENTARIO_DELETAR_FALURE";

export const CATEGORIAS_REQUEST = 'CATEGORIAS_REQUEST';
export const CATEGORIAS_FALURE = 'CATEGORIAS_FALURE';
export const CATEGORIAS_SUCCESS = 'CATEGORIAS_SUCCESS';

export const CRIAR_CATEGORIAS_REQUEST = 'CRIAR_CATEGORIAS_REQUEST';
export const CRIAR_CATEGORIAS_FALURE = 'CRIAR_CATEGORIAS_FALURE';
export const CRIAR_CATEGORIAS_SUCCESS = 'CRIAR_CATEGORIAS_SUCCESS';

export const EDITAR_CATEGORIAS_REQUEST = 'EDITAR_CATEGORIAS_REQUEST';
export const EDITAR_CATEGORIAS_FALURE = 'EDITAR_CATEGORIAS_FALURE';
export const EDITAR_CATEGORIAS_SUCCESS = 'EDITAR_CATEGORIAS_SUCCESS';

export const DELETAR_CATEGORIAS_REQUEST = 'DELETAR_CATEGORIAS_REQUEST';
export const DELETAR_CATEGORIAS_FALURE = 'DELETAR_CATEGORIAS_FALURE';
export const DELETAR_CATEGORIAS_SUCCESS = 'DELETAR_CATEGORIAS_SUCCESS';

export const SUBCATEGORIAS_REQUEST = 'SUBCATEGORIAS_REQUEST';
export const SUBCATEGORIAS_FALURE = 'SUBCATEGORIAS_FALURE';
export const SUBCATEGORIAS_SUCCESS = 'SUBCATEGORIAS_SUCCESS';

export const CRIAR_SUBCATEGORIAS_REQUEST = 'CRIAR_SUBCATEGORIAS_REQUEST';
export const CRIAR_SUBCATEGORIAS_FALURE = 'CRIAR_SUBCATEGORIAS_FALURE';
export const CRIAR_SUBCATEGORIAS_SUCCESS = 'CRIAR_SUBCATEGORIAS_SUCCESS';

export const EDITAR_SUBCATEGORIAS_REQUEST = 'EDITAR_SUBCATEGORIAS_REQUEST';
export const EDITAR_SUBCATEGORIAS_FALURE = 'EDITAR_SUBCATEGORIAS_FALURE';
export const EDITAR_SUBCATEGORIAS_SUCCESS = 'EDITAR_SUBCATEGORIAS_SUCCESS';

export const DELETAR_SUBCATEGORIAS_REQUEST = 'DELETAR_SUBCATEGORIAS_REQUEST';
export const DELETAR_SUBCATEGORIAS_FALURE = 'DELETAR_SUBCATEGORIAS_FALURE';
export const DELETAR_SUBCATEGORIAS_SUCCESS = 'DELETAR_SUBCATEGORIAS_SUCCESS';

export const CARGOS_REQUEST = 'CARGOS_REQUEST';
export const CARGOS_FALURE = 'CARGOS_FALURE';
export const CARGOS_SUCCESS = 'CARGOS_SUCCESS';

export const CRIAR_CARGO_REQUEST = 'CRIAR_CARGO_REQUEST';
export const CRIAR_CARGO_FALURE = 'CRIAR_CARGO_FALURE';
export const CRIAR_CARGO_SUCCESS = 'CRIAR_CARGO_SUCCESS';

export const EDITAR_CARGO_REQUEST = 'EDITAR_CARGO_REQUEST';
export const EDITAR_CARGO_FALURE = 'EDITAR_CARGO_FALURE';
export const EDITAR_CARGO_SUCCESS = 'EDITAR_CARGO_SUCCESS';

export const DELETAR_CARGO_REQUEST = 'DELETAR_CARGO_REQUEST';
export const DELETAR_CARGO_FALURE = 'DELETAR_CARGO_FALURE';
export const DELETAR_CARGO_SUCCESS = 'DELETAR_CARGO_SUCCESS';


export const ARQUIVO_CRIAR_REQUEST = "ARQUIVO_CRIAR_REQUEST";
export const ARQUIVO_CRIAR_SUCCESS = "ARQUIVO_CRIAR_SUCCESS";
export const ARQUIVO_CRIAR_FALURE = "ARQUIVO_CRIAR_FALURE";

export const ARQUIVO_EDITAR_REQUEST = "ARQUIVO_EDITAR_REQUEST";
export const ARQUIVO_EDITAR_SUCCESS = "ARQUIVO_EDITAR_SUCCESS";
export const ARQUIVO_EDITAR_FALURE = "ARQUIVO_EDITAR_FALURE";

export const ARQUIVO_BUSCAR_REQUEST = "ARQUIVO_BUSCAR_REQUEST";
export const ARQUIVO_BUSCAR_SUCCESS = "ARQUIVO_BUSCAR_SUCCESS";
export const ARQUIVO_BUSCAR_FALURE = "ARQUIVO_BUSCAR_FALURE";

export const ARQUIVO_DOWNLOAD_REQUEST = "ARQUIVO_DOWNLOAD_REQUEST";
export const ARQUIVO_DOWNLOAD_SUCCESS = "ARQUIVO_DOWNLOAD_SUCCESS";
export const ARQUIVO_DOWNLOAD_FALURE = "ARQUIVO_DOWNLOAD_FALURE";

export const ARQUIVO_DELETAR_REQUEST = "ARQUIVO_DELETAR_REQUEST";
export const ARQUIVO_DELETAR_SUCCESS = "ARQUIVO_DELETAR_SUCCESS";
export const ARQUIVO_DELETAR_FALURE = "ARQUIVO_DELETAR_FALURE";

// ----------

export const CHATS_CRIAR_REQUEST = "CHATS_CRIAR_REQUEST";
export const CHATS_CRIAR_SUCCESS = "CHATS_CRIAR_SUCCESS";
export const CHATS_CRIAR_FALURE = "CHATS_CRIAR_FALURE";

export const CHATS_CRIAR_COM_FOTO_REQUEST = "CHATS_CRIAR_COM_FOTO_REQUEST";
export const CHATS_CRIAR_COM_FOTO_SUCCESS = "CHATS_CRIAR_COM_FOTO_SUCCESS";
export const CHATS_CRIAR_COM_FOTO_FALURE = "CHATS_CRIAR_COM_FOTO_FALURE";

export const CHATS_EDITAR_REQUEST = "CHATS_EDITAR_REQUEST";
export const CHATS_EDITAR_SUCCESS = "CHATS_EDITAR_SUCCESS";
export const CHATS_EDITAR_FALURE = "CHATS_EDITAR_FALURE";

export const CHATS_EDITAR_COM_FOTO_REQUEST = "CHATS_EDITAR_COM_FOTO_REQUEST";
export const CHATS_EDITAR_COM_FOTO_SUCCESS = "CHATS_EDITAR_COM_FOTO_SUCCESS";
export const CHATS_EDITAR_COM_FOTO_FALURE = "CHATS_EDITAR_COM_FOTO_FALURE";

export const CHATS_BUSCAR_REQUEST = "CHATS_BUSCAR_REQUEST";
export const CHATS_BUSCAR_SUCCESS = "CHATS_BUSCAR_SUCCESS";
export const CHATS_BUSCAR_FALURE = "CHATS_BUSCAR_FALURE";

export const CHATS_DOWNLOAD_REQUEST = "CHATS_DOWNLOAD_REQUEST";
export const CHATS_DOWNLOAD_SUCCESS = "CHATS_DOWNLOAD_SUCCESS";
export const CHATS_DOWNLOAD_FALURE = "CHATS_DOWNLOAD_FALURE";

export const CHATS_DELETAR_REQUEST = "CHATS_DELETAR_REQUEST";
export const CHATS_DELETAR_SUCCESS = "CHATS_DELETAR_SUCCESS";
export const CHATS_DELETAR_FALURE = "CHATS_DELETAR_FALURE";

export const CHATS_ARQUIVO_DELETAR_REQUEST = "CHATS_ARQUIVO_DELETAR_REQUEST";
export const CHATS_ARQUIVO_DELETAR_SUCCESS = "CHATS_ARQUIVO_DELETAR_SUCCESS";
export const CHATS_ARQUIVO_DELETAR_FALURE = "CHATS_ARQUIVO_DELETAR_FALURE";